name: '[CD] Deploy Data Catalog'

on:
  workflow_dispatch:

  pull_request: 
    types:
      - closed
    branches:
      - main
    paths:
    - 'lab/adventure_works/**.yml'
    - 'lab/adventure_works/**.md'

permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  deploy:
    name: 'Deploy Data Catalog'
    runs-on: ubuntu-latest
    env:
      DBT_PROJECT_DIR: ${{ github.workspace }}/lab/adventure_works
      DBT_PROFILES_DIR: ${{ github.workspace }}/lab/profiles
      DBT_TARGET_PATH: ${{ github.workspace }}/lab/adventure_works/target
      SITE_PATH: ${{ github.workspace }}/site
      DUCKDB_DATA: ${{ github.workspace }}/lab/duckdb_data
      DWH_DATA: ${{ github.workspace }}/lab/dwh_data
      ADVENTURE_WORKS_SOURCE_URL: "https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/databases/adventure-works/oltp-install-script"
      REQUIREMENTS_FILE_PATH: ${{ github.workspace }}/.devcontainer/requirements.txt
    steps:
    - name: 'Checkout branch'
      uses: 'actions/checkout@v2'

    - name: 'Setup Python 3.10'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 'Cache virtualenv'
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: ${{ env.REQUIREMENTS_FILE_PATH }}

    - name: 'Restore cache'
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: 'Install dependencies'
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: |
        pip install -r ${{ env.REQUIREMENTS_FILE_PATH }}
    
    - name: 'Test database connection'
      run: dbt debug

    - name: 'Install dbt packages'
      run: dbt deps

    - name: 'Generate & Deploy Data Catalog'
      run: dbt docs generate
      
    - name: 'Move generated files to _site'
      run: |
        mkdir ${{ env.SITE_PATH }}
        mv ${{ env.DBT_TARGET_PATH }}/index.html ${{ env.SITE_PATH }}/
        mv ${{ env.DBT_TARGET_PATH }}/catalog.json ${{ env.SITE_PATH }}/
        mv ${{ env.DBT_TARGET_PATH }}/manifest.json ${{ env.SITE_PATH }}/
      
    - name: 'Upload GitHub Pages artifact'
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ${{ env.SITE_PATH }}
        
    - name: 'Deploy GitHub Pages site'
      uses: actions/deploy-pages@v2.0.1
